version: '3.8'
services:
  mongo:
      image: mongo:latest
      hostname: mongo
      container_name: mongo
      ports:
        - '27017:27017'
      logging:
        options:
            max-size: 1g
      environment:
        - MONGO_INITDB_DATABASE=my_db
        - MONGO_INITDB_ROOT_USERNAME=admin
        - MONGO_INITDB_ROOT_PASSWORD=123456
      volumes:
        - mongo_data:/data/db
      networks:
        - vps-net
volumes:
  mongo_data:
networks:
  vps-net:
    external: true
        