version: '3.8'
services:
  redis:
    container_name: redis
    image: bitnami/redis:latest
    ports:
      - '6379:6379'
    volumes: 
      - cache:/data
    environment:
      ALLOW_EMPTY_PASSWORD: yes
    networks:
      - vps-net
volumes:
  cache:
    driver: local
networks:
  vps-net:
    external: true