version: '3.8'
services:
  mongo:
      image: mongo:latest
      container_name: mongo
      ports:
        - '27016:27017'
      logging:
        options:
            max-size: 1g
      environment:
        - MONGO_INITDB_DATABASE=my_db
        - MONGO_INITDB_ROOT_USERNAME=admin
        - MONGO_INITDB_ROOT_PASSWORD=123456
      volumes:
        - mongo_data:/data/db
volumes:
  mongo_data:
        